
name: Redeploy React App to S3
'on':
  push:
    branches:
      - main
jobs:
  redeploy:
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.ACCESSKEY}}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.SECRETKEY }}'
          AWS_REGION: '${{ secrets.us-east-1}}'
          S3_BUCKET_NAME: '${{ secrets.staticsite01 }}'
        run: |
          aws s3 sync build/ s3://$staticsite01 --delete
