name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
        env :
        AWS-ACCESS-KEY-ID : ${{secrets.ACCESSKEY }}
        AWS-SECRET-KEY-ID : ${{secret.SECRETKEY}}
        AWS-REGION : us-east-1
        AWS-BUCKET : s3://demo-buckett-01

        run : aws s3 cp 
